name: SonarCloud analysis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: -Dsonar.projectKey="awells2399_website_portfolio"
            -Dsonar.organization="awells2399"
            -Dsonar.sources=static-website-src,lambda_functions
            -Dsonar.tests=lambda_functions/tests
            -Dsonar.language=js,py
            -Dsonar.inclusions=**/*.js,**/*.py
            -Dsonar.exclusions=**/node_modules/**,**/__tests__/**,**/venv/**
            -Dsonar.javascript.lcov.reportPaths=static-website-src/coverage/lcov.info
            -Dsonar.python.coverage.reportPaths=lambda_functions/coverage.xml
            -Dsonar.verbose=true
